/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/utilities/parsing.py:261: UserWarning: Attribute 'model' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['model'])`.
  rank_zero_warn(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Sanity Checking DataLoader 0: 100%|██████████████████████████████████████████████| 2/2 [00:00<00:00, 23.91it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
  | Name  | Type   | Params
---------------------------------
0 | model | ResNet | 11.2 M
---------------------------------
11.2 M    Trainable params
0         Non-trainable params
11.2 M    Total params
44.720    Total estimated model params size (MB)
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:487: PossibleUserWarning: Your `val_dataloader`'s sampler has shuffling enabled, it is strongly recommended that you turn shuffling off for val/test/predict dataloaders.
  rank_zero_warn(
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:229: UserWarning: You called `self.log('dim:', ...)` in your `validation_step` but the value needs to be floating point. Converting it to torch.float32.

Epoch 0:   8%|███▏                                     | 72/927 [00:01<00:19, 44.60it/s, loss=2.17, v_num=692q]
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.






Epoch 0:  91%|████████████████████████████████████▎   | 841/927 [00:16<00:01, 52.56it/s, loss=1.56, v_num=692q]








Epoch 1:  95%|█████████████████████████████████████▉  | 879/927 [00:16<00:00, 53.46it/s, loss=1.39, v_num=692q]







Epoch 2:  82%|████████████████████████████████▋       | 757/927 [00:14<00:03, 50.86it/s, loss=1.19, v_num=692q]








Epoch 3:  86%|██████████████████████████████████▎     | 794/927 [00:15<00:02, 51.34it/s, loss=1.07, v_num=692q]








Epoch 4:  86%|█████████████████████████████████▎     | 793/927 [00:15<00:02, 49.83it/s, loss=0.988, v_num=692q]








Epoch 5:  86%|█████████████████████████████████▌     | 799/927 [00:15<00:02, 50.46it/s, loss=0.816, v_num=692q]








Epoch 6:  91%|███████████████████████████████████▋   | 847/927 [00:15<00:01, 52.96it/s, loss=0.681, v_num=692q]








Epoch 7:  94%|████████████████████████████████████▍  | 867/927 [00:16<00:01, 52.47it/s, loss=0.625, v_num=692q]








Epoch 8:  96%|█████████████████████████████████████▌ | 892/927 [00:16<00:00, 52.83it/s, loss=0.542, v_num=692q]







Epoch 9:  82%|███████████████████████████████▉       | 758/927 [00:15<00:03, 50.20it/s, loss=0.405, v_num=692q]








Epoch 10:  84%|███████████████████████████████▊      | 777/927 [00:15<00:02, 50.24it/s, loss=0.344, v_num=692q]

Validation DataLoader 0: 100%|███████████████████████████████████████████████| 185/185 [00:02<00:00, 79.23it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, test_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:229: UserWarning: You called `self.log('test accuracy: ', ...)` in your `test_step` but the value needs to be floating point. Converting it to torch.float32.









Testing DataLoader 0: 100%|███████████████████████████████████████████████| 7178/7178 [00:19<00:00, 368.27it/s]
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
     test accuracy:         0.5363610982894897
